version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - DB=postgres
      - DATABASE_URL=postgres://postgres:postgres@db:5432/spree_development

  db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: spree_development
    ports:
      - "5432:5432"

volumes:
  postgres-data: 